### PR TITLE
Removing non functional states and maps with those states

### PR DESCRIPTION
**Pull request by sophiekummer**
Leaving only functional states and maps in JSONs.
For a win state to be functional, it has to be included in the GState class, with a function that determines when this state is reached. Both of the maps added had a new win state that were not added to GState, and therefore will never be marked as having reached the win state.

### CODE REVIEW

**Review by Graham-Berry — CHANGES_REQUESTED** [review]
Can we do some sort of preservation of this work before I approve? Possibly copying into (currently) non-functional jsons that could be added to documentation folder for future work?  These are good ideas and could be made functional with a little more work and I would hate for these to be straight-up nuked.

**Comment by sophiekummer** [comment]
> Can we do some sort of preservation of this work before I approve? Possibly copying into (currently) non-functional jsons that could be added to documentation folder for future work? These are good ideas and could be made functional with a little more work and I would hate for these to be straight-up nuked.

My plan was to add this to the future work section in the documentation (with code snippets and screenshots if possible) later in the week, but if you would like to see it happen within this branch I can do it here.

**Review by Hodgdonc — APPROVED** [review]
I agree with Graham, as long as they are preserved at some point I am fine with this change.

**Comment by sophiekummer** [comment]
> > Can we do some sort of preservation of this work before I approve? Possibly copying into (currently) non-functional jsons that could be added to documentation folder for future work? These are good ideas and could be made functional with a little more work and I would hate for these to be straight-up nuked.
> 
> My plan was to add this to the future work section in the documentation (with code snippets and screenshots if possible) later in the week, but if you would like to see it happen within this branch I can do it here.

Documentation got added in the todo.md for knockout. I think that I was maybe going insane last night and that capture the flag does have a valid win state so I put it back, but if I could get a second set of eyes on that I would greatly appreciate.
@Graham-Berry @Hodgdonc

**Review by Graham-Berry — APPROVED** [review]

**Pull request merged**
